# Generated by Django 4.0.4 on 2022-10-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cart_orders_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
