# Generated by Django 4.0.4 on 2022-10-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_business_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
