# Generated by Django 4.0.4 on 2022-10-22 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_business_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
